CREATE TABLE Poezd (
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
НОМП VARCHAR(255) NOT NULL,
ИНДЕКС_ПОЕЗДА VARCHAR(255) NOT NULL,
СТАНЦ VARCHAR(255) NOT NULL,
ОПЕР VARCHAR(255) NOT NULL,
ДАТА_ВРЕМЯ DATETIME NOT NULL);

CREATE TABLE Vagon (
id INT AUTO_INCREMENT NOT NULL,
НП INT(255) NOT NULL,
НОМ.ВАГ INT(255) NOT NULL,
ВЕС INT(255) NOT NULL,
СТАНЦ VARCHAR(255) NOT NULL,
ПРИЗНАКИ VARCHAR(255) NOT NULL,
ДЕПО VARCHAR(255) NOT NULL,
ПРИП VARCHAR(255) NOT NULL,
id_poezd INT NOT NULL,
PRIMARY KEY (id,id_poezd));

ALTER TABLE Vagon ADD CONSTRAINT Vagon_id_poezd_Poezd_id FOREIGN KEY (id_poezd) REFERENCES Poezd(id);